experiment:
  name: "stacking_sift_rgbsift"
  description: "Stack SIFT with RGBSIFT"
  version: "1.0"
  author: "researcher"

dataset:
  type: "hpatches"
  path: "../data/"

keypoints:
  generator: "sift"
  max_features: 1500
  source: "homography_projection"

descriptors:
  - name: "stack_sift_rgb"
    type: "sift"
    pooling: "stacking"
    secondary_descriptor: "rgbsift"
    stacking_weight: 0.5
    normalize_after_pooling: true

evaluation:
  matching:
    method: "brute_force"
    norm: "l2"
    cross_check: true
    threshold: 0.8
  validation:
    method: "homography"
    threshold: 0.05
    min_matches: 10

database:
  connection: "sqlite:///experiments.db"

